#define K_TAB            9
#define K_ENTER         13
#define K_ESC           27
#define K_SPACE         32
#define K_EXCLAMATION   33
#define K_QUOTE         34
#define K_NUM_SIGN      35
#define K_DOLLAR        36
#define K_PERCENT       37
#define K_AND           38
#define K_SINGLE_QUOTE  39
#define K_LEFT_BRACKET  40
#define K_RIGHT_BRACKET 41
#define K_STAR          42
#define K_PLUS          43
#define K_COMMA         44
#define K_DASH          45
#define K_PERIOD        46
#define K_FRONT_SLASH   47
#define K_0             48
#define K_1             49
#define K_2             50
#define K_3             51
#define K_4             52
#define K_5             53
#define K_6             54
#define K_7             55
#define K_8             56
#define K_9             57
#define K_COLON         58
#define K_SEMICOLON     59
#define K_LESS_THAN     60
#define K_EQUAL         61
#define K_GREATER_THAN  62
#define K_QUESTION      63
#define K_AT            64
#define K_A             65
#define K_B             66
#define K_C             67
#define K_D             68
#define K_E             69
#define K_F             70
#define K_G             71
#define K_H             72
#define K_I             73
#define K_J             74
#define K_K             75
#define K_L             76
#define K_M             77
#define K_N             78
#define K_O             79
#define K_P             80
#define K_Q             81
#define K_R             82
#define K_S             83
#define K_T             84
#define K_U             85
#define K_V             86
#define K_W             87
#define K_X             88
#define K_Y             89
#define K_Z             90
#define K_SQUARE_LEFT   91
#define K_BACK_SLASH    92
#define K_SQUARE_RIGHT  93
#define K_HAT           94
#define K_UNDERSCORE    95
#define K_TICK          96
#define K_a             97
#define K_b             98
#define K_c             99
#define K_d             100
#define K_e             101
#define K_f             102
#define K_g             103
#define K_h             104
#define K_i             105
#define K_j             106
#define K_k             107
#define K_l             108
#define K_m             109
#define K_n             110
#define K_o             111
#define K_p             112
#define K_q             113
#define K_r             114
#define K_s             115
#define K_t             116
#define K_u             117
#define K_v             118
#define K_w             119
#define K_x             120
#define K_y             121
#define K_z             122
#define K_BRACE_LEFT    123
#define K_VERT_LINE     124
#define K_BRACE_RIGHT   125
#define K_SQUIGLY       126
#define K_DEL           127
#define K_RIGHT_SHIFT   54
#define K_PRINT_SCREEN  55
#define K_ALT           56
#define K_CAPS_LOCK     58
#define K_F1            315
#define K_F2            316
#define K_F3            317
#define K_F4            318
#define K_F5            319
#define K_F6            320
#define K_F7            321
#define K_F8            322
#define K_F9            323
#define K_F10           324
#define K_F11           133
#define K_F12           134
#define K_NUM_LOCK      69
#define K_SCROLL_LOCK   70
#define K_HOME          71
#define K_UP            72
#define K_PAGE_UP       73
#define K_LEFT          75
#define K_RIGHT         77
#define K_END           79
#define K_DOWN          80
#define K_PAGE_DOWN     81
#define K_INSERT        82
